#!/bin/sh
for f in *.batt; do
    echo -n "Testing $f... "
    if dune exec batt -- $f > /dev/null 2>&1; then
        echo "did not fail but was expected to!"
        exit 1
    else
        echo "failed as expected."
    fi
done
