(menhir
 (modules parser)
 ; (flags --strict --unused-token INCLUDE)
)

(executable
 (public_name batt)
 (libraries sedlex menhirLib unix)
 (preprocess (pps ppx_deriving.show sedlex.ppx))
 (promote (until-clean))
)

(rule
 (alias runtest)
 (deps test.batt)
 (action (run ./batt.exe -I ../stdlib test.batt))
)
