(executable
 (name batt)
 (modes js)
 (preprocess (pps js_of_ocaml-ppx))
 (libraries js_of_ocaml batt)
)

(rule
 (targets fs.js)
 (deps (source_tree ../stdlib))
 (action
   (run js_of_ocaml build-fs -o fs.js ../stdlib:/static/stdlib)
 )
)

(install
 (files index.html batt.css batt.js)
 (package batt)
 (section share)
)
